server:
  port: 8080
  contextPath: /
  request:
    maxBodySize: 2048mb
    maxHeaderSize: 20mb
  session:
    timeout: 7200 #单位秒；（可不配，默认：7200）



jwt:
  name: TOKEN #变量名；（可不配，默认：TOKEN）
  secret: "IDP32XTulsVIUZU+srFEUC9Lhu1wV+nd8iCJPoPA2zSFVAtWhCgpMEymxy5wFAZKMB9yROX31UjDzjwL66r1RA==" #密钥（使用 JwtUtils.createKey() 生成）；
#  prefix: Bearer #令牌前缀（可不配，默认：空）
  allowExpire: true #充许超时；（可不配，默认：true）；false，则token一直有效
  allowAutoIssue: false #充许自动输出；（可不配，默认：true）；flase，则不向header 或 cookie 设置值（由用户手动控制）
  allowUseHeader: true #充许使用Header传递；（可不配，默认：使用 Cookie 传递）；true，则使用 header 传递
  expire: 864000000 # token超时时间，单位为毫秒

repo:
  external-url:
  type: local
  local:
    # 默认为$HOME/bdcm/local_repo
    path:
    listen: 0.0.0.0:9980
  s3:
    endpoint:
    bucket:
    accessKey:
    secretKey:

grab:
  http-headers:
    - name: User-Agent
      #value: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
      value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"
#      value: "curl/7.88.1"
    - name: Connection
      value: keep-alive
  http-proxy:
    enable: ${HTTP_PROXY_ENABLE:false}
    host: ${HTTP_PROXY_HOST:}
    port: ${HTTP_PROXY_PORT:}
    exclude: ${HTTP_PROXY_EXCLUDE:127.0.0.1,mirrors.ustc.edu.cn,localhost,192.168.66.0/24}
  https-proxy:
    enable: ${HTTPS_PROXY_ENABLE:${grab.httpProxy.enable:}}
    host: ${HTTPS_PROXY_HOST:${grab.httpProxy.host:}}
    port: ${HTTPS_PROXY_PORT:${grab.httpProxy.port:}}
    exclude: ${HTTPS_PROXY_EXCLUDE:${grab.httpProxy.exclude:}}




solon:
#  debug: 1
  app:
    name: bdcm
  view:
    mapping:
      html: FreemarkerRender
  logging:
    logger:
      "io.undertow":
        level: "WARN"
    appender:
      console:
        level: INFO
      file:
        level: INFO
        maxFileSize: "1 MB"
        maxHistory: "7"
  serialization:
    json:
      longAsString: true #将long型转为字符串输出 （默认为false）


spring:
  database:
    type: h2
  datasource:
    url:
    username:
    password:

#spring:
#  database:
#    type: mysql
#  datasource:
#    url: jdbc:mysql://192.168.66.122:3306/bdcm?characterEncoding=utf-8&useSSL=false&autoReconnect=true
#    username: root
#    password: 666666
#
#spring:
#  database:
#    type: mysql
#  datasource:
#    url: jdbc:mysql://192.168.66.122:13306/bdcm?characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
#    username: root
#    password: 666666
#
#spring:
#  database:
#    type: postgresql
#  datasource:
#    url: jdbc:postgresql://192.168.66.122:5432/bdcm?&ssl=false
#    username: postgres
#    password: 666666
#
#spring:
#  database:
#    type: sqlite
#  datasource:
#    url:
#    username:
#    password: